### PR TITLE
html update 2

### PR DESCRIPTION
**Pull request by sam-halfpenny**
big thanks to Jackm on this one. you are the worlds best website designer

### CODE REVIEW

**Comment by will-0** [comment]
Yo niiiiiiiiiiiiice

**Comment by will-0** [comment]
@sam-halfpenny do you wanna set Jackm up as an editor for this repository? Could be good for him to start getting some Github contributions, will be helpful for future job applications etc x

**Comment by will-0** [comment]
Also happy to transfer ownership over to you at some point if you'd like :) might have to have a quick check of any legal stuff but should be fine imo

**Review by will-0 — APPROVED** [review]
Jazzy

**Comment by sam-halfpenny** [comment]
yeah. I might add jack, he is on a repository with me atm for his python but i think it would probably make it easier if he was on this one

**Comment by sam-halfpenny** [comment]
his username is March-j

**Pull request merged**
