### PR TITLE
other stuff ttpage and risk calculator (bare statistics tecas)

### PR DESCRIPTION
**Pull request by sam-halfpenny**

### CODE REVIEW

**Comment by sam-halfpenny** [comment]
hold on that's not correct don't accept it yet ill try and fix it

**Comment by sam-halfpenny** [comment]
ok its all good to go now

**Review by will-0 — APPROVED** [review]
Lol, I'm not gonna check your maths but the code works :) maybe you should build in a limit to how many players can be entered into the box, as it crashes if there's too many.

Someone wrote a paper on this: https://www4.stat.ncsu.edu/~jaosborn/research/RISK.pdf

**Comment by will-0** [comment]
Unfortunately the maths for this one is not correct :( you can check your answers against the ground truth listed in that paper, e.g. your chance of winning is >0.5 for attacker having 5, defender having 5.

**Comment by sam-halfpenny** [comment]
oh maybe but i would have thought that the probability of winning 5 on 5
would be lower than 0.5 as the attacker would only be able to lose 4 times
and the defender could lose 5 times especially since there is a higher
chance of the defender winning a dice roll (7/12) than the attacker (5/12).

**Comment by will-0** [comment]
Ah yeah you're right, the paper counts having 5 people in a country as having 4 attackers (since 1 always has to stay). However, the probabilities are still off I'm afraid: e.g. your calculator says 6vs5 will still favour the defender

**Comment by sam-halfpenny** [comment]
i would have thought it would

**Comment by sam-halfpenny** [comment]
i dont quite understand the paper but table:1 did mention the no. dice
rolled whereas my calculator only works out the outcome when rolling one
dice

**Comment by will-0** [comment]
Duuuuuuuuuude. At no point did you mention that, that's a pretty crucial point lol.

**Comment by sam-halfpenny** [comment]
ummmmmmm whoops

**Comment by sam-halfpenny** [comment]
dad worked out that rolling 1 dice is more efficient than rolling three

**Comment by will-0** [comment]
Well I don't know what he means by "efficient", but it reduces your chance of winning a battle as the attacker for a lot of scenarios.

This is what we're doing in the lesson today so we can do it then!

**Comment by sam-halfpenny** [comment]
sweet

**Pull request merged**
