### PR TITLE
asteroids

### PR DESCRIPTION
**Pull request by sam-halfpenny**

### CODE REVIEW

**Comment by will-0** [comment]
Yo this is sick!!!!

**Review by will-0 — APPROVED** [review]
Yeah bruuuuuu this is sick!!! This game is super fun to play, is fast and I haven't seen any glitches - aka, a smash hit.

I'm really impressed with this game, I think it's got some complex stuff going on here. This calls for something: I think it's code presentation time, baby. Let's find a time for you to explain this code to me, particularly how you've done the collision detection, rotation, and the separation after you shoot the asteroids. 

This pull request is definitely #approooooooved

**Comment by will-0** [comment]
(From now on I'm gonna do reviews but leave you to merge pull requests, so you keep control of when stuff on your website changes)

**Comment by will-0** [comment]
And look at this beautiful network graph 😍
image

**Comment by sam-halfpenny** [comment]
yh would love to find a time to talk to you about how i went about doing the collision detection and other stuff im free most of the time (because i am a pro😎) and would love to chat

**Pull request merged**
